In [ ]:
## Numpy arrays and basics
learn about python with chai aur code

In [3]:
import numpy as np

In [5]:
### creating array from list

In [7]:
arr_1d = np.array([1,2,3,4,5])
print("1D array",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array",arr_2d)

1D array [1 2 3 4 5]
2D array [[1 2 3]
 [4 5 6]]


In [9]:
### List vs numpy arra

In [12]:
py_list = [1,2,3]
print("Python list multiplication",py_list * 2)

np_array = np.array([1,2,3]) #element wise multiplication
print("Python list multiplication",np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000)]
print("\n List Operation time:",time.time() - start)

start = time.time()
np_array = np.arange(1000) * 2
print("\nNumpy operation time:",time.time() - start)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python list multiplication [2 4 6]

 List Operation time: 0.00022482872009277344

Numpy operation time: 0.003902435302734375


In [13]:
### creating array from scratch

In [14]:
zerox = np.zeros((3,4))
print("zerox array:\n",zerox)

zerox array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
onex = np.ones((2,3))
print("onex array: \n",onex)

onex array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
full = np.full((2,2),7)
print("full array: \n",full)

full array: 
 [[7 7]
 [7 7]]


In [18]:
random = np.random.random((2,3))
print("random array:\n",random)

random array:
 [[0.83501089 0.35203318 0.90424704]
 [0.55527589 0.80365867 0.50740278]]


In [22]:
sequence = np.arange(0,11,2)
print("sequence array:\n",sequence)

sequence array:
 [ 0  2  4  6  8 10]


In [23]:
### Vector, Matrix and Tensor

In [25]:
vector = np.array([1,2,3])
print("Vector:",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix: ",matrix)

tensor = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print("Tensor array:\n ",tensor)

Vector: [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor array:
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
### Array Properties

In [29]:
arr = np.array([[1,2,3],
                 [4,5,6]])
print("shape :",arr.shape)
print("Dimension:", arr.ndim)
print("Size:",arr.size)
print("Datatype",arr.dtype)

shape : (2, 3)
Dimension: 2
Size: 6
Datatype int64


In [30]:
### Array Reshaping

In [36]:
arr = np.arange(12)
print("Original array:",arr)

reshaped = arr.reshape((3,4))
print("\nReshaped array: \n",reshaped)

flattend = reshaped.flatten()
print("\n Flattened Array", flattend)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
# ravel (returns view, insted of copy)
raveled = reshaped.ravel()
print("\n raveled array : ",raveled)



 raveled array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
#Transpose
transpose = reshaped.T
print("\t Transposed array:",transpose)

	 Transposed array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
